### PR TITLE
Fix pp admin exporter

### PR DESCRIPTION
**Pull request by Quentinchampenois**
### Describe
As an admin, when trying to export a participatory space JSON file, I don't receive the email.

#### More information
Server error is due to an empty hero image url or banner image url.

### CODE REVIEW

**Review by paulinebessoles — COMMENTED** [review]
Thank you @Quentinchampenois! 
I tested in local, and in the letter_opener, after I exported a pp, I can see that a mail was sent but cannot see the content. 
I don't know if it's a letter opener problem, because other emails are displayed ok. 
Capture d’écran 2021-05-03 à 18 32 02

**Comment by Quentinchampenois** [comment]
Hi @paulinebessoles, interesting I have not seen this behaviour. 
I will check again asap to be sure, thanks !

**Comment by Quentinchampenois** [comment]
@paulinebessoles I have tested again, it seems to work, the email is not blank. 
And I don't think that this fix can occur a blank email

**Comment by paulinebessoles** [comment]
Okay, that's good news! 😁 I merge then (and yes to check together ahah)

**Pull request merged**
