### PR TITLE
Feature/add friendly signup

### PR DESCRIPTION
**Pull request by Quentinchampenois**
#### DEscription

Add friendly signup and keep extra fields added

#### Done

- Add friendly signup system specs
- Update specs
- Update Rack Attack configuration
-

### CODE REVIEW

**Review by armandfardeau — APPROVED** [review]

**Review by paulinebessoles — APPROVED** [review]
Thank you it works for me @Quentinchampenois! I'm just wondering about the utility to keep the app/packs/src/decidim/user_registrations.js file, IMO we don't need to override it anymore, what do you think?

**Comment by armandfardeau** [comment]
Switching back to draft until @paulinebessoles question is resolved

**Comment by Quentinchampenois** [comment]
> Thank you it works for me @Quentinchampenois! I'm just wondering about the utility to keep the `app/packs/src/decidim/user_registrations.js` file, IMO we don't need to override it anymore, what do you think?

Hey ! we must keep this file because it holds logic for hiding / showing city fields and representative email

**Comment by Quentinchampenois** [comment]
As we should keep the JS file, I reopen this PR

**Pull request merged**
