### PR TITLE
Add missing linked assemblies flag

### PR DESCRIPTION
**Pull request by Quentinchampenois**
Admin should be able to define if linked assemblies should be displayed for a PP

Backport of https://github.com/OpenSourcePolitics/decidim/pull/948/files

### CODE REVIEW

**Review by paulinebessoles — CHANGES_REQUESTED** [review]
Hi @Quentinchampenois ! Thanks for these changes, I just noticed some missing items :) 

- When "Display linked assemblies flag" is disabled on a participatory process, linked assemblies still appear on the process group card of the PP
- When "Display linked assemblies flag" is enabled, linked assemblies are only displayed on the PP card--mini and on the PP banner. So it's missing on the PP highlighted card and on the PP card--process in /processes
I'm available to discuss it if needed

**Comment by Quentinchampenois** [comment]
Hi @paulinebessoles, 

According to your change request I have added linked assemblies in participatory processes and PP group. 
Cf Screenshot bellow
Screenshot 2021-04-08 at 18 18 23

And ensure that linked assemblies are not displayed in process view

Hope it is was expected

**Review by armandfardeau — CHANGES_REQUESTED** [review]
Hi @Quentinchampenois.
May you check the failing test? It is not a flaky.

**Comment by Quentinchampenois** [comment]
Hi @armandfardeau,

I don't understand why it is failing on CI, in local environment I don't have those failing tests. Keep investigating

**Review by armandfardeau — APPROVED** [review]

**Pull request merged**
